export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_LIVESTREAM_BEGIN = "GET_LIVESTREAM_BEGIN";
export const GET_LIVESTREAM_SUCCESS = "GET_LIVESTREAM_SUCCESS";

export const GET_ANNOUNCEMENTS_BEGIN = "GET_ANNOUNCEMENTS_BEGIN";
export const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";

export const GET_EVENT_BEGIN = "GET_EVENT_BEGIN";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";

export const GET_FORMS_BEGIN = "GET_FORMS_BEGIN";
export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";

export const GET_PRAYERCATEGORY_BEGIN = "GET_PRAYERCATEGORY_BEGIN";
export const GET_PRAYERCATEGORY_SUCCESS = "GET_PRAYERCATEGORY_SUCCESS";

export const GET_TESTIMONYCATEGORY_BEGIN = "GET_TESTIMONYCATEGORY_BEGIN";
export const GET_TESTIMONYCATEGORY_SUCCESS = "GET_TESTIMONYCATEGORY_SUCCESS";

export const GET_SAVEDPRAYER_BEGIN = "GET_SAVEDPRAYER_BEGIN";
export const GET_SAVEDPRAYER_SUCCESS = "GET_SAVEDPRAYER_SUCCESS";

export const CREATE_PRAYER_BEGIN = "CREATE_PRAYER_BEGIN";
export const CREATE_PRAYER_SUCCESS = "CREATE_PRAYER_SUCCESS";
export const CREATE_PRAYER_ERROR = "CREATE_PRAYER_ERROR";

export const CREATE_TESTIMONY_BEGIN = "CREATE_TESTIMONY_BEGIN";
export const CREATE_TESTIMONY_SUCCESS = "CREATE_TESTIMONY_SUCCESS";
export const CREATE_TESTIMONY_ERROR = "CREATE_TESTIMONY_ERROR";

export const GET_PRAYER_BEGIN = "GET_PRAYER_BEGIN";

export const CREATE_FORM_BEGIN = "CREATE_FORM_BEGIN";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const CREATE_FORM_ERROR = "CREATE_FORM_ERROR";

export const GET_LEARNING_BEGIN = "GET_LEARNING_BEGIN";
export const GET_LEARNING_SUCCESS = "GET_LEARNING_SUCCESS";

export const GET_VOLUNTEER_BEGIN = "GET_VOLUNTEER_BEGIN";
export const GET_VOLUNTEER_SUCCESS = "GET_VOLUNTEER_SUCCESS";

export const CHECK_ENROLLMENT_BEGIN = "CHECK_ENROLLMENT_BEGIN";
export const CHECK_ENROLLMENT_SUCCESS = "CHECK_ENROLLMENT_SUCCESS";

export const GET_ENROLLEDCOURSES_BEGIN = "GET_ENROLLEDCOURSES_BEGIN";
export const GET_ENROLLEDCOURSES_SUCCESS = "GET_ENROLLEDCOURSES_SUCCESS";

export const EDIT_MEMBER_BEGIN = "EDIT_MEMBER_BEGIN";
export const EDIT_MEMBER_SUCCESS = "EDIT_MEMBER_SUCCESS";
export const EDIT_MEMBER_ERROR = "EDIT_MEMBER_ERROR";

export const UPDATE_USERPASSWORD_BEGIN = "UPDATE_USERPASSWORD_BEGIN";
export const UPDATE_USERPASSWORD_SUCCESS = "UPDATE_USERPASSWORD_SUCCESS";
export const UPDATE_USERPASSWORD_ERROR = "UPDATE_USERPASSWORD_ERROR";

export const GET_GROWTHPLANNER_BEGIN = "GET_GROWTHPLANNER_BEGIN";
export const GET_GROWTHPLANNER_SUCCESS = "GET_GROWTHPLANNER_SUCCESS";

CREATE_GROWTHPLANNER_BEGIN = "CREATE_GROWTHPLANNER_BEGIN";
CREATE_GROWTHPLANNER_SUCCESS = "CREATE_GROWTHPLANNER_SUCCESS";
CREATE_GROWTHPLANNER_ERROR = "CREATE_GROWTHPLANNER_ERROR";
